on:
  issues:
    types: [labeled]
  workflow_dispatch:
    inputs:
      reason:
        required: true
        default: true
        type: boolean

jobs:
  update-readme-table:
    timeout-minutes: 3
    if: github.event.label.name == 'stats' || github.event.inputs.tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - run: |
          nimble install decimal -y && \
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" nim c -d:ssl -r src/mktable.nim readme && \
          mv -f README.md.new README.md
      - uses: EndBug/add-and-commit@v7
        with:
          add: "README.md"
          author_name: Robot
          message: 'Auto-update'
          push: true

